spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ss
    username: root
    password: xingbo
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8080

logging:
  level:
    com.ss.mapper: debug
